version: '2.4'

services:
  app:
    image: 'andriosi/product:1.0.0-SNAPSHOT'
    build:
      context: .
    container_name: app
    depends_on:
      db:
        condition: service_healthy
    environment:
      - QUARKUS_DATASOURCE_JDBC_URL=jdbc:postgresql://db:5432/productdb
      - QUARKUS_DATASOURCE_USERNAME=quarkus
      - QUARKUS_DATASOURCE_PASSWORD=@Quarkus0076
      - QUARKUS_FLYWAY_MIGRATE_AT_START=true
    ports:
      - 8081:8081
    networks:
      - product-db-net

  db:
    image: 'postgres:17.1-alpine'
    container_name: db
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=quarkus
      - POSTGRES_PASSWORD=@Quarkus0076
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U quarkus"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - product-db-net

networks:
  product-db-net:
    name: product-db-net
